[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "transcript-redaction"
dynamic = ["version"]

dependencies = [
    'easyocr',
    'opencv-python',
    'PyMuPDF',
    'nltk'
]